project:
  type: website
  output-dir: docs

website:
  title: "Eric Kim"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Consumer Behavior"
        href: consumer-behavior.html
      - text: "Résumé"
        href: resume.html

format:
  html:
    theme: [flatly, theme.scss]
    toc: true
    toc-location: left